"""
Splitwise WhatsApp Reminder Bot
Author: Siddh Bhadani
Description: Fetches outstanding balances from Splitwise API and sends 
             automated WhatsApp reminders to friends who owe money.
"""

import urllib3
import json
import os
import sys
import logging
import requests
import pywhatkit
from dotenv import load_dotenv
import time
from typing import Dict, List, Set, Any

# ================== CONFIGURATION & LOGGING ==================

# Setup logging to track successes and failures
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

load_dotenv()

# Environment Variables
API_KEY = os.getenv("SPLITWISE_API_KEY")
BASE_URL = "https://secure.splitwise.com/api/v3.0"
FRIENDS_FILE = "friends.json"
AUTHOR_NAME = os.getenv("AUTHOR_NAME")
AUTHOR_EMAIL = os.getenv("AUTHOR_EMAIL")

# SECURITY: Hard cap to prevent spam
MAX_MESSAGES_PER_RUN = 5
MESSAGE_DELAY_SECONDS = 20  # SECURITY: rate limiting

# ================== VALIDATION ==================

if not API_KEY:
    logging.critical("Invalid or missing SPLITWISE_API_KEY in .env file.")
    sys.exit(1)

# ================== DATA LOADING ==================

def load_phone_book(file_path: str) -> Dict[str, str]:
    """Loads phone numbers from a JSON file and normalizes keys to lowercase."""
    if not os.path.exists(file_path):
        logging.error(f"Configuration file '{file_path}' not found!")
        return {}
    
    try:
        with open(file_path, "r") as f:
            data = json.load(f)
            # Ensure all keys are lowercase for consistent matching
            return {str(k).lower(): str(v) for k, v in data.items()}
    except json.JSONDecodeError:
        logging.error(f"Invalid JSON format in {file_path}")
        return {}
    except Exception as e:
        logging.error(f"Could not load phone book: {e}")
        return {}

# ================== CORE FUNCTIONS ==================

def get_splitwise_friends() -> List[Dict[str, Any]]:
    """Fetches list of friends and their balances from Splitwise API."""
    headers = {"Authorization": f"Bearer {API_KEY}"}
    try:
        response = requests.get(f"{BASE_URL}/get_friends", headers=headers, timeout=10)
        response.raise_for_status()  
        return response.json().get("friends", [])
    except requests.exceptions.RequestException as e:
        logging.error(f"Failed to connect to Splitwise API: {e}")
        return []


def sanitize_message(text: str) -> str:
    """SECURITY: Remove problematic characters for WhatsApp Web."""
    return text.replace('"', "'").strip()

def generate_message(name: str, amount: float, currency: str = "CAD") -> str:
    """Formats the reminder message."""
    return sanitize_message(
        f"Hey {name} 👋\n\n"
        f"Just a quick reminder that you owe me {amount:.2f} {currency} "
        f"from our Splitwise expenses.\n"
        f"Could you please clear it within this week😊??\n\n"
        f"Thanks!"
        f"This is my Email: {AUTHOR_EMAIL}\n"
        f"Autodeposit is on under {AUTHOR_NAME}\\n\n"
        f"Automated message generated by Splitwise Reminder Bot."
    )
    
def mask_phone(phone: str) -> str:
    """SECURITY: Avoid logging full phone numbers."""
    return phone[:3] + "****" + phone[-2:]

def send_whatsapp_reminder(phone_no: str, message: str, friend_name: str):
    """Handles the automation of sending a WhatsApp message."""
    try:
        logging.info(f"Attempting to send message to {friend_name} {mask_phone(phone_no)}...")
        # wait_time: seconds to wait before sending (adjust based on internet speed)
        # tab_close: automatically closes the browser tab after sending
        pywhatkit.sendwhatmsg_instantly(
            phone_no=phone_no,
            message=message,
            wait_time=15,  # Increased to 20s to 25s for better reliability on slower PCs
            tab_close=True,
            close_time=3
        )
        logging.info(f"Successfully queued WhatsApp message for {friend_name}.")

        time.sleep(MESSAGE_DELAY_SECONDS) 
    except Exception as e:
        logging.error(f"WhatsApp automation failed for {friend_name}: {e}")
        logging.debug(e)

# ================== MAIN EXECUTION ==================
def main():
    if not API_KEY:
        logging.critical("SPLITWISE_API_KEY missing in .env")
        return

    # Load data from external JSON
    phone_book = load_phone_book(FRIENDS_FILE)
    
    # DEBUG: See what names were actually loaded
    logging.info(f"Phone book loaded with keys: {list(phone_book.keys())}")

    if not phone_book:
        logging.error("Phone book is empty or friends.json is missing. Exiting.")
        return

    friends = get_splitwise_friends()
    sent_users: Set[str] = set()
    messages_sent = 0

    for friend in friends:
        if messages_sent >= MAX_MESSAGES_PER_RUN:
            logging.info("Run limit reached for this session.")
            break

        first_name = (friend.get("first_name") or "").strip()
        last_name = (friend.get("last_name") or "").strip()
        name_key = first_name.lower()
        full_name = f"{first_name} {last_name}".strip()
        
        if not first_name or name_key in sent_users:
            continue

        # Check balances FIRST
        for balance in friend.get("balance", []):
            try:
                amount = float(balance.get("amount", 0))
                currency = balance.get("currency_code", "CAD")
                
                # Only look for a phone number if they owe you money (> 0)
                if amount > 0.01: # Check for more than 1 cent
                    phone_no = phone_book.get(name_key)
                    
                    if phone_no:
                        msg = generate_message(first_name, amount, currency)
                        send_whatsapp_reminder(phone_no, msg, full_name)
                        
                        sent_users.add(name_key)
                        messages_sent += 1
                        break # Only send one message per friend
                    else:
                        # Only warn if they owe money but have no phone number
                        logging.warning(f"ACTION REQUIRED: {full_name} owes {amount} {currency}, but no phone number found in friends.json.")
                
            except Exception as e:
                logging.error(f"Error processing balance for {first_name}: {e}")

if __name__ == "__main__":
    urllib3.disable_warnings(urllib3.exceptions.NotOpenSSLWarning)
    
    logging.info("Starting Splitwise Reminder Bot...")
    try:
        main()
    finally:
        if os.path.exists("PyWhatKit_DB.txt"):
            try:
                os.remove("PyWhatKit_DB.txt")
            except Exception:
                open("PyWhatKit_DB.txt", "w").close()
    logging.info("Process completed.")
